packages:
  - 'packages/*'
  - 'libs/*'
  - 'apps/*'
allowBuilds:
  '@google/genai': false
  '@nestjs/core': false
  '@parcel/watcher': false
  '@prisma/client': false
  '@prisma/engines': false
  '@scarf/scarf': false
  '@swc/core': false
  better-sqlite3: false
  cypress: false
  detox: false
  dtrace-provider: false
  esbuild: false
  less: false
  msgpackr-extract: false
  nx: false
  prisma: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@nx/cypress@22.7.3'
  - '@nx/detox@22.7.3'
  - '@nx/devkit@22.7.3'
  - '@nx/docker@22.7.3'
  - '@nx/eslint-plugin@22.7.3'
  - '@nx/eslint@22.7.3'
  - '@nx/expo@22.7.3'
  - '@nx/jest@22.7.3'
  - '@nx/js@22.7.3'
  - '@nx/module-federation@22.7.3'
  - '@nx/nest@22.7.3'
  - '@nx/next@22.7.3'
  - '@nx/node@22.7.3'
  - '@nx/nx-darwin-arm64@22.7.3'
  - '@nx/nx-darwin-x64@22.7.3'
  - '@nx/nx-freebsd-x64@22.7.3'
  - '@nx/nx-linux-arm-gnueabihf@22.7.3'
  - '@nx/nx-linux-arm64-gnu@22.7.3'
  - '@nx/nx-linux-arm64-musl@22.7.3'
  - '@nx/nx-linux-x64-gnu@22.7.3'
  - '@nx/nx-linux-x64-musl@22.7.3'
  - '@nx/nx-win32-arm64-msvc@22.7.3'
  - '@nx/nx-win32-x64-msvc@22.7.3'
  - '@nx/react-native@22.7.3'
  - '@nx/react@22.7.3'
  - '@nx/rollup@22.7.3'
  - '@nx/vite@22.7.3'
  - '@nx/vitest@22.7.3'
  - '@nx/web@22.7.3'
  - '@nx/webpack@22.7.3'
  - '@nx/workspace@22.7.3'
  - nx@22.7.3
