const { hairlineWidth } = require('nativewind/theme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        'app-primary-1': '#4640DE',
        'app-primary-2': '#4F46E5',
        'app-secondary-1': '#26A4FF',
        'app-secondary-2': '#0EA5E9',
        'app-text-1': '#202430',
        'app-text-2': '#7C8493',
        'app-text-3': '#475569',
        'app-background-1': '#EEF2FF',
        'app-white-1': '#FFFFFF',
        'app-border-1': '#D6DDEB',
        'app-border-2': '#CBD5E1',
        'app-border-3': '#E6E8F0',
        'app-emerald-1': '#EBF9F1',
        'app-emerald-2': '#56CDAD',
        'app-emerald-3': '#2DD4BF',
        'app-amber-1': '#FFB836',
        'app-amber-2': '#F59E0B',
        'app-slate-1': '#0F172A',
        'app-red-1': '#EF4444',
        'app-green-1': '#22C55E',
        'app-pink-1': '#EC4899',
        'app-text-4': '#25324B',
        'app-text-5': '#64748B',
        'app-purple-1': '#A855F7',
        'app-teal-1': '#14B8A6',
        'app-yellow-1': '#EAB308',
        'app-rose-1': '#E11D48',
        'app-indigo-1': '#6366F1',
        'app-orange-1': '#EA580C',
        'app-slate-2': '#E2E8F0',
        'app-red-2': '#DC2626',
        'app-gray-1': '#E5E7EB',
        'app-gray-2': '#374151',
        'app-neutral-1': '#FAFAFA',
        'app-brand-text': '#121419',
        'app-background-2': '#F8F9FE',
        'app-red-3': '#FF4444',
        'app-indigo-soft': '#E0E7FF',
        'app-indigo-strong': '#4338CA',
        'app-slate-gray': '#F1F5F9',
        'app-text-gray': '#667085',
        'app-card-header': '#5B5CE7',
        'app-gray-3': '#6B7280',
        'app-border-light': '#dbe1ee',
        'app-dark-text': '#111827',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      borderWidth: {
        hairline: hairlineWidth(),
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  future: {
    hoverOnlyWhenSupported: true,
  },
  plugins: [require('tailwindcss-animate')],
};
