import { type HiringStage } from '@/features/employer/job-listing/detail/data';

export interface AllApplicant {
  id: string;
  name: string;
  image: string;
  appliedDate: string;
  score: number;
  hiringStage: HiringStage;
  appliedRole: string;
}

export const allApplicants: AllApplicant[] = [
  // ── 2020 ──────────────────────────────────────────────
  {
    id: '1',
    name: 'Alice Johnson',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
    appliedDate: '2020-05-21',
    score: 8.2,
    hiringStage: 'Hired',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '2',
    name: 'Bob Smith',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    appliedDate: '2020-05-22',
    score: 6.7,
    hiringStage: 'Declined',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '3',
    name: 'Carol Lee',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carol',
    appliedDate: '2020-05-23',
    score: 8.5,
    hiringStage: 'Interviewed',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '4',
    name: 'Ethan Park',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan',
    appliedDate: '2020-05-23',
    score: 6.9,
    hiringStage: 'Shortlisted',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '5',
    name: 'Fatima Al-Hassan',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
    appliedDate: '2020-05-24',
    score: 8.1,
    hiringStage: 'In Review',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '6',
    name: 'George Chen',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=George',
    appliedDate: '2020-05-24',
    score: 6.4,
    hiringStage: 'Declined',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '7',
    name: 'Hannah Müller',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hannah',
    appliedDate: '2020-05-25',
    score: 8.7,
    hiringStage: 'Hired',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '8',
    name: 'Ivan Petrov',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ivan',
    appliedDate: '2020-05-25',
    score: 6.2,
    hiringStage: 'Declined',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '9',
    name: 'Jessica Okafor',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica',
    appliedDate: '2020-05-26',
    score: 8.0,
    hiringStage: 'Interviewed',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '10',
    name: 'Kevin Tanaka',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin',
    appliedDate: '2020-05-26',
    score: 3.8,
    hiringStage: 'Shortlisted',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '11',
    name: 'Laura Martínez',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Laura',
    appliedDate: '2020-05-27',
    score: 4.3,
    hiringStage: 'Interviewed',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '12',
    name: 'Marcus Williams',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    appliedDate: '2020-05-27',
    score: 3.5,
    hiringStage: 'In Review',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '13',
    name: 'Nina Johansson',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nina',
    appliedDate: '2020-05-28',
    score: 8.6,
    hiringStage: 'Shortlisted',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '14',
    name: 'Omar Farouk',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Omar',
    appliedDate: '2020-05-28',
    score: 6.1,
    hiringStage: 'Declined',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '15',
    name: 'Priya Sharma',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    appliedDate: '2020-05-29',
    score: 7.4,
    hiringStage: 'In Review',
    appliedRole: 'Social Media Assistant',
  },
  // Carol Lee also applied for Senior Designer
  {
    id: '3',
    name: 'Carol Lee',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carol',
    appliedDate: '2020-05-17',
    score: 7.8,
    hiringStage: 'Shortlisted',
    appliedRole: 'Senior Designer',
  },
  {
    id: '16',
    name: 'Raj Patel',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Raj',
    appliedDate: '2020-08-03',
    score: 7.1,
    hiringStage: 'Hired',
    appliedRole: 'Backend Developer',
  },
  {
    id: '17',
    name: 'Sophie Dubois',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie',
    appliedDate: '2020-09-14',
    score: 5.9,
    hiringStage: 'Declined',
    appliedRole: 'Content Writer',
  },
  {
    id: '18',
    name: 'Tomás Rivera',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tomas',
    appliedDate: '2020-11-02',
    score: 8.3,
    hiringStage: 'Hired',
    appliedRole: 'Senior Designer',
  },

  // ── 2021 ──────────────────────────────────────────────
  {
    id: '19',
    name: 'Amara Osei',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amara',
    appliedDate: '2021-01-10',
    score: 7.6,
    hiringStage: 'Interviewed',
    appliedRole: 'Frontend Developer',
  },
  {
    id: '20',
    name: "Liam O'Brien",
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Liam',
    appliedDate: '2021-02-18',
    score: 9.1,
    hiringStage: 'Hired',
    appliedRole: 'Frontend Developer',
  },
  // Alice Johnson also applied for Project Manager
  {
    id: '1',
    name: 'Alice Johnson',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
    appliedDate: '2021-03-05',
    score: 7.5,
    hiringStage: 'Interviewed',
    appliedRole: 'Project Manager',
  },
  {
    id: '21',
    name: 'Yuki Nakamura',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Yuki',
    appliedDate: '2021-04-22',
    score: 6.8,
    hiringStage: 'Shortlisted',
    appliedRole: 'Data Analyst',
  },
  {
    id: '22',
    name: 'Elena Voronova',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
    appliedDate: '2021-06-15',
    score: 8.4,
    hiringStage: 'Hired',
    appliedRole: 'Backend Developer',
  },
  {
    id: '23',
    name: 'Daniel Kim',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel',
    appliedDate: '2021-07-30',
    score: 5.2,
    hiringStage: 'Declined',
    appliedRole: 'Content Writer',
  },
  {
    id: '24',
    name: 'Chloe Nguyen',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe',
    appliedDate: '2021-09-12',
    score: 7.9,
    hiringStage: 'In Review',
    appliedRole: 'Product Manager',
  },
  // Bob Smith also applied for Data Analyst
  {
    id: '2',
    name: 'Bob Smith',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    appliedDate: '2021-10-08',
    score: 5.4,
    hiringStage: 'Declined',
    appliedRole: 'Data Analyst',
  },
  {
    id: '25',
    name: 'Mikhail Kozlov',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mikhail',
    appliedDate: '2021-11-19',
    score: 7.0,
    hiringStage: 'Shortlisted',
    appliedRole: 'DevOps Engineer',
  },

  // ── 2022 ──────────────────────────────────────────────
  {
    id: '26',
    name: 'Aisha Mohammed',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha',
    appliedDate: '2022-01-25',
    score: 8.8,
    hiringStage: 'Hired',
    appliedRole: 'Product Manager',
  },
  {
    id: '27',
    name: 'James Walker',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    appliedDate: '2022-03-09',
    score: 4.6,
    hiringStage: 'Declined',
    appliedRole: 'Frontend Developer',
  },
  // Ethan Park also applied for Backend Developer
  {
    id: '4',
    name: 'Ethan Park',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan',
    appliedDate: '2022-04-11',
    score: 7.3,
    hiringStage: 'Interviewed',
    appliedRole: 'Backend Developer',
  },
  {
    id: '28',
    name: 'Isabella Costa',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella',
    appliedDate: '2022-05-20',
    score: 6.5,
    hiringStage: 'In Review',
    appliedRole: 'UX Researcher',
  },
  {
    id: '29',
    name: 'Lucas Bergström',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas',
    appliedDate: '2022-06-30',
    score: 9.0,
    hiringStage: 'Hired',
    appliedRole: 'DevOps Engineer',
  },
  {
    id: '30',
    name: 'Mei Lin',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mei',
    appliedDate: '2022-08-04',
    score: 7.7,
    hiringStage: 'Shortlisted',
    appliedRole: 'Data Analyst',
  },
  {
    id: '31',
    name: 'Noah Fischer',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Noah',
    appliedDate: '2022-09-18',
    score: 5.8,
    hiringStage: 'Declined',
    appliedRole: 'Marketing Coordinator',
  },
  // Jessica Okafor also applied for Product Manager
  {
    id: '9',
    name: 'Jessica Okafor',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica',
    appliedDate: '2022-10-05',
    score: 8.3,
    hiringStage: 'Hired',
    appliedRole: 'Product Manager',
  },
  {
    id: '32',
    name: 'Sara Lindqvist',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sara',
    appliedDate: '2022-11-22',
    score: 6.0,
    hiringStage: 'Interviewed',
    appliedRole: 'Content Writer',
  },

  // ── 2023 ──────────────────────────────────────────────
  {
    id: '33',
    name: 'Adrian Popescu',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Adrian',
    appliedDate: '2023-01-14',
    score: 7.2,
    hiringStage: 'Shortlisted',
    appliedRole: 'Backend Developer',
  },
  {
    id: '34',
    name: 'Zara Khan',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Zara',
    appliedDate: '2023-02-28',
    score: 8.9,
    hiringStage: 'Hired',
    appliedRole: 'Senior Designer',
  },
  // Hannah Müller also applied for UX Researcher
  {
    id: '7',
    name: 'Hannah Müller',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hannah',
    appliedDate: '2023-03-16',
    score: 9.2,
    hiringStage: 'Hired',
    appliedRole: 'UX Researcher',
  },
  {
    id: '35',
    name: 'Victor Andrei',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Victor',
    appliedDate: '2023-04-09',
    score: 4.1,
    hiringStage: 'Declined',
    appliedRole: 'DevOps Engineer',
  },
  {
    id: '36',
    name: 'Olivia Thompson',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia',
    appliedDate: '2023-05-21',
    score: 7.5,
    hiringStage: 'Interviewed',
    appliedRole: 'Marketing Coordinator',
  },
  {
    id: '37',
    name: 'Hassan El-Amin',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hassan',
    appliedDate: '2023-06-07',
    score: 6.3,
    hiringStage: 'In Review',
    appliedRole: 'Frontend Developer',
  },
  {
    id: '38',
    name: 'Maria Santos',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    appliedDate: '2023-07-19',
    score: 8.1,
    hiringStage: 'Shortlisted',
    appliedRole: 'Project Manager',
  },
  // Kevin Tanaka also applied for Frontend Developer
  {
    id: '10',
    name: 'Kevin Tanaka',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin',
    appliedDate: '2023-08-22',
    score: 5.6,
    hiringStage: 'In Review',
    appliedRole: 'Frontend Developer',
  },
  {
    id: '39',
    name: 'Freya Jørgensen',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Freya',
    appliedDate: '2023-09-30',
    score: 7.8,
    hiringStage: 'Interviewed',
    appliedRole: 'Data Analyst',
  },
  {
    id: '40',
    name: 'David Okonkwo',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    appliedDate: '2023-11-11',
    score: 8.5,
    hiringStage: 'Hired',
    appliedRole: 'Backend Developer',
  },

  // ── 2024 ──────────────────────────────────────────────
  {
    id: '41',
    name: 'Emma Svensson',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    appliedDate: '2024-01-08',
    score: 6.6,
    hiringStage: 'Shortlisted',
    appliedRole: 'Content Writer',
  },
  {
    id: '42',
    name: 'Ryan Mitchell',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan',
    appliedDate: '2024-02-14',
    score: 9.3,
    hiringStage: 'Hired',
    appliedRole: 'DevOps Engineer',
  },
  // Priya Sharma also applied for Data Analyst
  {
    id: '15',
    name: 'Priya Sharma',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    appliedDate: '2024-03-01',
    score: 8.0,
    hiringStage: 'Interviewed',
    appliedRole: 'Data Analyst',
  },
  {
    id: '43',
    name: 'Leo Moretti',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Leo',
    appliedDate: '2024-04-17',
    score: 5.1,
    hiringStage: 'Declined',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '44',
    name: 'Nadia Volkov',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nadia',
    appliedDate: '2024-05-23',
    score: 7.4,
    hiringStage: 'In Review',
    appliedRole: 'UX Researcher',
  },
  {
    id: '45',
    name: 'Oscar Reyes',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Oscar',
    appliedDate: '2024-06-10',
    score: 8.6,
    hiringStage: 'Shortlisted',
    appliedRole: 'Product Manager',
  },
  // Nina Johansson also applied for Marketing Coordinator
  {
    id: '13',
    name: 'Nina Johansson',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nina',
    appliedDate: '2024-07-05',
    score: 7.9,
    hiringStage: 'Hired',
    appliedRole: 'Marketing Coordinator',
  },
  {
    id: '46',
    name: 'Grace Adeyemi',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Grace',
    appliedDate: '2024-08-19',
    score: 4.7,
    hiringStage: 'Declined',
    appliedRole: 'Senior Designer',
  },
  {
    id: '47',
    name: 'Samuel Eriksson',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Samuel',
    appliedDate: '2024-09-28',
    score: 6.9,
    hiringStage: 'Interviewed',
    appliedRole: 'Project Manager',
  },
  {
    id: '48',
    name: 'Ling Wei',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ling',
    appliedDate: '2024-11-06',
    score: 8.2,
    hiringStage: 'Hired',
    appliedRole: 'Frontend Developer',
  },

  // ── 2025 ──────────────────────────────────────────────
  {
    id: '49',
    name: 'Maya Jefferson',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maya',
    appliedDate: '2025-01-15',
    score: 7.3,
    hiringStage: 'Shortlisted',
    appliedRole: 'Backend Developer',
  },
  // Omar Farouk also applied for DevOps Engineer
  {
    id: '14',
    name: 'Omar Farouk',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Omar',
    appliedDate: '2025-02-20',
    score: 7.7,
    hiringStage: 'Interviewed',
    appliedRole: 'DevOps Engineer',
  },
  {
    id: '50',
    name: 'Isla Campbell',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isla',
    appliedDate: '2025-03-12',
    score: 5.5,
    hiringStage: 'In Review',
    appliedRole: 'Content Writer',
  },
  {
    id: '51',
    name: 'Arjun Reddy',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun',
    appliedDate: '2025-04-04',
    score: 9.0,
    hiringStage: 'Hired',
    appliedRole: 'Data Analyst',
  },
  {
    id: '52',
    name: 'Clara Hoffmann',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Clara',
    appliedDate: '2025-05-18',
    score: 6.2,
    hiringStage: 'Declined',
    appliedRole: 'Marketing Coordinator',
  },
  // Laura Martínez also applied for Product Manager
  {
    id: '11',
    name: 'Laura Martínez',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Laura',
    appliedDate: '2025-06-09',
    score: 7.1,
    hiringStage: 'Shortlisted',
    appliedRole: 'Product Manager',
  },
  {
    id: '53',
    name: 'Felix Dubois',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
    appliedDate: '2025-07-22',
    score: 8.4,
    hiringStage: 'Interviewed',
    appliedRole: 'Senior Designer',
  },
  {
    id: '54',
    name: 'Thandiwe Nkosi',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Thandiwe',
    appliedDate: '2025-08-30',
    score: 4.9,
    hiringStage: 'Declined',
    appliedRole: 'Social Media Assistant',
  },
  {
    id: '55',
    name: 'Kenji Watanabe',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kenji',
    appliedDate: '2025-10-14',
    score: 7.6,
    hiringStage: 'In Review',
    appliedRole: 'UX Researcher',
  },
  {
    id: '56',
    name: 'Rosalie Fournier',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rosalie',
    appliedDate: '2025-11-25',
    score: 8.8,
    hiringStage: 'Hired',
    appliedRole: 'Project Manager',
  },

  // ── 2026 ──────────────────────────────────────────────
  {
    id: '57',
    name: 'Alexander Novak',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alexander',
    appliedDate: '2026-01-06',
    score: 6.7,
    hiringStage: 'In Review',
    appliedRole: 'Backend Developer',
  },
  // Fatima Al-Hassan also applied for Frontend Developer
  {
    id: '5',
    name: 'Fatima Al-Hassan',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
    appliedDate: '2026-01-20',
    score: 8.5,
    hiringStage: 'Shortlisted',
    appliedRole: 'Frontend Developer',
  },
  {
    id: '58',
    name: 'Beatrice Mwangi',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Beatrice',
    appliedDate: '2026-02-03',
    score: 7.0,
    hiringStage: 'Interviewed',
    appliedRole: 'Data Analyst',
  },
  {
    id: '59',
    name: 'Henrik Larsen',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Henrik',
    appliedDate: '2026-02-17',
    score: 5.3,
    hiringStage: 'Declined',
    appliedRole: 'Content Writer',
  },
  // Marcus Williams also applied for DevOps Engineer
  {
    id: '12',
    name: 'Marcus Williams',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    appliedDate: '2026-02-25',
    score: 6.8,
    hiringStage: 'Shortlisted',
    appliedRole: 'DevOps Engineer',
  },
  {
    id: '60',
    name: 'Valentina Rossi',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Valentina',
    appliedDate: '2026-03-08',
    score: 9.1,
    hiringStage: 'In Review',
    appliedRole: 'Product Manager',
  },
  // George Chen also applied for Marketing Coordinator
  {
    id: '6',
    name: 'George Chen',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=George',
    appliedDate: '2026-03-10',
    score: 7.2,
    hiringStage: 'Interviewed',
    appliedRole: 'Marketing Coordinator',
  },
];
